### ISSUE TITLE
Unassign a task

### ISSUE THREAD

**Issue by alvarocasadoc** [infusionvlc/ConexionFelina#100]
I'm a **volunteer**,
I want to **unassign a task to a colony**,
so that I **no longer keep track of work related with this task**.

**Comment by jodoldar** [comment]
Once an user has been logged in as a Volunteer, the next steps should be followed:

- Go to the url: covi.es/colonies
- Click on the Colony to modify the assignment
- In the list of Assignments, select the one to be removed
- Once in the Assigment page, click on the _Destroy_ button
