### ISSUE TITLE
Delete a task

### ISSUE THREAD

**Issue by alvarocasadoc** [infusionvlc/ConexionFelina#101]
I'm a **volunteer**,
I want to **delete a task from the list**,
so that **it no longer exists**.
It should also delete all assignments relative to this task in any colony.

**Comment by jodoldar** [comment]
Once an user has been logged in as a Volunteer, the next steps should be followed:

- Go to the url: covi.es/tasks
- Click on the Task to be deleted
- In the Task, select the _Destroy_ button
