### ISSUE TITLE
Edit a task

### ISSUE THREAD

**Issue by alvarocasadoc** [infusionvlc/ConexionFelina#102]
I'm a **volunteer**,
I want to **edit a task from the list**,
so that **I can update its details**.

**Comment by jodoldar** [comment]
Once an user has been logged in as a Volunteer, the next steps should be followed:

- Go to the url: covi.es/tasks
- Click on the Task to be edited
- In the Task, select the _Edit_ button
- In the form, modify the fields of the Task required
- Click on the Update Task button
