### ISSUE TITLE
Component: Button

### ISSUE THREAD

**Issue by alvarocasadoc** [infusionvlc/ConexionFelina#127]
# Overview
Hey! :wave: We're looking for someone like you to implement this React component along with Storybook. You can see its details by visiting the [design specification docs](https://www.figma.com/file/PuezufmBksh475JS5nvBsSkx/ConexionFelina?node-id=0%3A1).

This is part of the new app design (#126) :art:

**Comment by iswanj** [comment]
Hi, For the first issue I would like to do this task and later I'll do other components as well. also, do I need to write unit tests for these components?

**Comment by alvarocasadoc** [comment]
Hi, iswanj! Thank you so much for your interest. I'll assign you this issue. 🙌

Also, writing some unit tests is a requirement. We have set up Jest along with our project, but if you have any questions or suggestions feel free to ask 😉

**Comment by alvarocasadoc** [comment]
Yes! You can find some little docs we have regarding our front-end dependencies:

https://github.com/infusionvlc/ConexionFelina/wiki/Front-end-development

**Comment by iswanj** [comment]
Using styled component or CSS modules instead of using sass(global styling). any thoughts?

**Comment by alvarocasadoc** [comment]
We are working with CSS modules. All current development work is in the `react` branch of the project, so make sure you start working from there. The client code is on `app/javascript` folder.

Here's an example of a component with its style:
https://github.com/infusionvlc/ConexionFelina/tree/react/app/javascript/bundles/UI/components/Input

If you have further suggestions don't hesitate to open new issues or discuss them here :wink:

**Comment by alvarocasadoc** [comment]
We haven't made a decision yet. So, as you are the first contributor writing tests, feel free to choose whatever you are more confortable with. I have no personal preference over any of them. :+1:
