### ISSUE TITLE
Component: Switch (check box)

### ISSUE THREAD

**Issue by alvarocasadoc** [infusionvlc/ConexionFelina#130]
# Overview
Hey! :wave: We're looking for someone like you to implement this React component along with Storybook. You can see its details by visiting the [design specification docs](https://www.figma.com/file/PuezufmBksh475JS5nvBsSkx/ConexionFelina?node-id=0%3A1).

This is part of the new app design (#126) :art:

**Comment by powens** [comment]
If you don't mind, I can work on this.

**Comment by alvarocasadoc** [comment]
Hi, Patrick! :wave:  

We're really happy to hear that. Thank you so much for expressing your interest on this issue. On the [Figma document](https://www.figma.com/file/PuezufmBksh475JS5nvBsSkx/ConexionFelina?node-id=0%3A1) you will find a little example of the desired look and feel. 

We are currently working on a CSS specification for every component, but meanwhile feel free to start working on the implementation, testing and even styling :triangular_ruler: :wrench: :art:

Also, check out our wiki page on [front-end development](https://github.com/infusionvlc/ConexionFelina/wiki/Front-end-development) to get things ready and start working :books: 

If you have any questions don't hesitate to ask :wink:

**Comment by powens** [comment]
Sounds good :smile: 

Would you prefer the component to be controlled, or uncontrolled?

**Comment by powens** [comment]
I've gone ahead and done a basic version. Feel free to let me know if there is anything you'd like changed :smile:
