### ISSUE TITLE
Component: TextArea

### ISSUE THREAD

**Issue by alvarocasadoc** [infusionvlc/ConexionFelina#131]
# Overview
Hey! :wave: We're looking for someone like you to implement this React component along with Storybook. You can see its details by visiting the [design specification docs](https://www.figma.com/file/PuezufmBksh475JS5nvBsSkx/ConexionFelina?node-id=0%3A1).

This is part of the new app design (#126) :art:

**Comment by MuneebJS** [comment]
Hi, I would like to work on it.
I've visited your provided link but I didn't understand what was going on.

**Comment by alvarocasadoc** [comment]
Right now there's one person working on this issue as you may see on the 'Assignees' section. Feel free to take a look onto other components. The Figma document works as a visual reference for the components design
