### ISSUE TITLE
Component: Sidebar

### ISSUE THREAD

**Issue by alvarocasadoc** [infusionvlc/ConexionFelina#134]
# Overview
Hey! :wave: We're looking for someone like you to implement this React component along with Storybook. You can see its details by visiting the [design specification docs](https://www.figma.com/file/PuezufmBksh475JS5nvBsSkx/ConexionFelina?node-id=0%3A1).

This is part of the new app design (#126) :art:

**Comment by iswanj** [comment]
@alvarocasadoc If this task is not assigned to anybody, I'd like to this.

**Comment by alvarocasadoc** [comment]
Yes! Feel free to work on it. Thank you so much! 🙌

**Comment by iswanj** [comment]
Hi, @alvarocasadoc please tell me, which font family they have used for this design?

**Comment by alvarocasadoc** [comment]
We're using Raleway font https://fonts.google.com/specimen/Raleway
