### ISSUE TITLE
Component: Avatar

### ISSUE THREAD

**Issue by alvarocasadoc** [infusionvlc/ConexionFelina#135]
# Overview
Hey! :wave: We're looking for someone like you to implement this React component along with Storybook. You can see its details by visiting the [design specification docs](https://www.figma.com/file/PuezufmBksh475JS5nvBsSkx/ConexionFelina?node-id=0%3A1).

This is part of the new app design (#126) :art:

**Comment by powens** [comment]
I can work on this issue 😄 

Is this the Avatar? 
![image](https://user-images.githubusercontent.com/1919554/46977277-9b053080-d080-11e8-8fb6-47a83aba857f.png)

**Comment by alvarocasadoc** [comment]
Hey, Patrick! Thanks for expressing your interest on this one. :raised_hands:  That's the app logo, but the avatar is quite similar too:

![image](https://user-images.githubusercontent.com/7248474/47029085-f6abe880-d16a-11e8-9233-94c6102bd96e.png)


It's basically a round image without borders. We used this gradient as a placeholder.
