### ISSUE TITLE
Component: Progress Bar

### ISSUE THREAD

**Issue by alvarocasadoc** [infusionvlc/ConexionFelina#139]
# Overview
Hey! :wave: We're looking for someone like you to implement this React component along with Storybook. You can see its details by visiting the [design specification docs](https://www.figma.com/file/PuezufmBksh475JS5nvBsSkx/ConexionFelina?node-id=0%3A1).

This is part of the new app design (#126) :art:

**Comment by Sergeytroinin** [comment]
Hey. I would be happy take it if no more volunteers here.

**Comment by alvarocasadoc** [comment]
Feel free to work on this issue. No one's working on it at the moment. In the Figma document you'll see a visual guide for the component styling.

Also, check out our wiki to start off working: https://github.com/infusionvlc/ConexionFelina/wiki/Front-end-development

If you have any questions or suggestions don't hesitate to ask! :wink:

**Comment by jodoldar** [comment]
> Hey. I would be happy take it if no more volunteers here.

Are you still working on this? @dredonieto would like to prepare this issue
