### ISSUE TITLE
Component: Picture

### ISSUE THREAD

**Issue by alvarocasadoc** [infusionvlc/ConexionFelina#142]
# Overview
Hey! :wave: We're looking for someone like you to implement this React component along with Storybook. You can see its details by visiting the [design specification docs](https://www.figma.com/file/PuezufmBksh475JS5nvBsSkx/ConexionFelina?node-id=0%3A1).

This is part of the new app design (#126) :art:

**Comment by jodoldar** [comment]
The Picture component has been added to solve the issue #142. This new component has three arguments:

- Size: it could be ('s', 'm', 'b'). `max-width: 200px, 400px, 800px`

- Alt_text: Typical alternative text for an image. For the attribute `<img alt="..." .../>`

- Source: Source for the _img_ tag. `<img src="..." .../>`
