### ISSUE TITLE
Assign a task to a colony

### ISSUE THREAD

**Issue by alvarocasadoc** [infusionvlc/ConexionFelina#99]
I'm a **volunteer**,
I want to **assign a task to a colony**,
so that I can  **keep track of all volunteers work related to this task**.

**Comment by jodoldar** [comment]
Once an user has been logged in as a Volunteer, the next steps should be followed:

- Go to the url: covi.es/colonies
- Click on the _Assign task_ button
- In the new page, select a Task from the list available (the Colony should be auto-selected)
- Click in the _Assign_ button
